from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('patient_dashboard/', views.patient_dashboard, name='patient_dashboard'),
    path('patient/profile/', views.update_profile, name='update_profile'),
    path('patient/pharmacies/', views.registered_pharmacies, name='registered_pharmacies'),
    path('patient/pharmacy/<int:pk>/medicines/', views.pharmacy_medicines, name='pharmacy_medicines'),
    path('patient/cart/add/<int:medicine_id>/', views.add_to_cart, name='add_to_cart'),
    path('patient/cart/update/<int:item_id>/<str:action>/', views.update_cart_quantity, name='update_cart_quantity'),
    path('patient/cart/course_duration/', views.update_cart_course_duration, name='update_cart_course_duration'),
    path('patient/cart/remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('patient/cart/', views.view_cart, name='view_cart'),
    path('patient_checkout/', views.checkout, name='checkout'),
    path('patient_records/', views.patient_records, name='patient_records'),
    path('patient_orders/', views.patient_orders, name='patient_orders'),
    path('patient/doctors/', views.view_doctors, name='view_doctors'),
    path('patient/appointments/', views.patient_appointments, name='patient_appointments'),
    path('patient/doctor/<int:doctor_id>/book-appointment/', views.book_appointment, name='book_appointment'),
    path('patient/prescriptions/', views.patient_prescriptions, name='patient_prescriptions'),
    path('patient/prescription/<int:prescription_id>/download/', views.download_prescription_pdf, name='download_prescription_pdf'),
    path('patient/upload-prescription/', views.upload_prescription, name='upload_prescription'),
    path('patient/upload-prescription/<int:pharmacist_id>/', views.upload_prescription, name='upload_prescription_specific'),
    path('patient/my-prescriptions/', views.view_my_prescriptions, name='view_my_prescriptions'),
    path('patient/delete-prescription/<int:prescription_id>/', views.delete_prescription_upload, name='delete_prescription_upload'),
    path('patient/add-prescription-medicines/<int:prescription_id>/', views.add_all_prescription_medicines_to_cart, name='add_all_prescription_medicines_to_cart'),
    path('pharmacist/prescription-uploads/', views.pharmacist_prescription_uploads, name='pharmacist_prescription_uploads'),
    path('patient/notifications/', views.patient_notifications, name='patient_notifications'),
    path('patient/appointment/<int:appointment_id>/rate/', views.submit_rating, name='submit_rating'),
    path('patient/order/<int:order_id>/rate/', views.submit_rating, name='submit_order_rating'),

    path('admin_profile/', views.admin_profile, name='admin_profile'),
    path('admin_doctors/', views.manage_doctors, name='manage_doctors'),
    path('doctor/dashboard/', views.doctor_dashboard, name='doctor_dashboard'),
    path('doctor/profile/', views.doctor_profile, name='doctor_profile'),
    path('doctor/appointments/', views.doctor_appointments, name='doctor_appointments'),
    path('doctor/appointment/<int:appointment_id>/status/', views.update_appointment_status, name='update_appointment_status'),
    path('doctor/appointment/<int:appointment_id>/reschedule/', views.reschedule_appointment, name='reschedule_appointment'),
    path('doctor/patients/', views.doctor_patients, name='doctor_patients'),
    path('doctor/ratings/', views.doctor_ratings_feedback, name='doctor_ratings_feedback'),
    path('doctor/appointment/<int:appointment_id>/prescribe/', views.add_prescription, name='add_prescription'),
    path('doctor/patient/<int:patient_id>/prescriptions/', views.patient_prescriptions_by_doctor, name='patient_prescriptions_by_doctor'),
    path('doctor/prescription/<int:prescription_id>/copy/', views.copy_prescription, name='copy_prescription'),
    path('doctor/prescription/<int:prescription_id>/delete/', views.delete_prescription, name='delete_prescription'),
    path('pharmacist/dashboard/', views.pharmacist_dashboard, name='pharmacist_dashboard'),
    path('pharmacist_profile/', views.pharmacist_profile, name='pharmacist_profile'),
    path('pharmacist/inventory/', views.pharmacist_inventory, name='pharmacist_inventory'),
    path('pharmacist/restock/', views.pharmacist_restock, name='pharmacist_restock'),
    path('pharmacist/medicine/edit/<int:pk>/', views.edit_medicine, name='edit_medicine'),
    path('pharmacist/orders/', views.pharmacist_orders, name='pharmacist_orders'),
    path('pharmacist/order/<int:order_id>/update-status/', views.update_order_status, name='update_order_status'),
    path('pharmacist/customers/', views.pharmacist_customers, name='pharmacist_customers'),
    path('pharmacist/ratings-feedback/', views.pharmacist_ratings_feedback, name='pharmacist_ratings_feedback'),
    path('pharmacist/reminders/send/<int:order_item_id>/', views.send_refill_reminder, name='send_refill_reminder'),
    path('api/check_medicine_stock/', views.check_medicine_stock, name='check_medicine_stock'),
    path('api/update_doctor_status/', views.update_doctor_status, name='update_doctor_status'),
    path('test/doctor_status/', views.test_doctor_status, name='test_doctor_status'),
    path('doctor/set_leave/', views.set_doctor_leave, name='set_doctor_leave'),
    path('admin_audit-logs/', views.admin_audit_logs, name='admin_audit_logs'),
        
    path('admin_patients/', views.manage_patients, name='manage_patients'),
    path('admin_medications/', views.medication_management, name='medication_management'),
    path('admin_reports/', views.generate_report, name='generate_report'),
    path('admin_reports_medications/csv/', views.export_medications_csv, name='export_medications_csv'),
    path('admin_reports_patients/pdf/', views.export_patient_registry_pdf, name='export_patient_registry_pdf'),
    path('admin_reports_finance/xlsx/', views.export_financial_summary_xlsx, name='export_financial_summary_xlsx'),
    path('admin_finance/', views.financial_oversight, name='financial_oversight'),
    path('admin_ratings_feedback/', views.admin_ratings_feedback, name='admin_ratings_feedback'),
    
    path('logout/', views.logout, name='logout'),
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)