# Generated by Django 6.0.1 on 2026-01-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_doctor_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacist",
            name="pharmacy_name",
            field=models.CharField(default="Local Pharmacy", max_length=200),
        ),
    ]
