# Generated by Django 6.0.1 on 2026-01-16 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_pharmacist_pharmacy_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=200)),
                ("generic_name", models.CharField(max_length=200)),
                ("strength", models.CharField(max_length=100)),
                ("formulation", models.CharField(max_length=100)),
                ("indications", models.TextField()),
                ("batch_number", models.CharField(max_length=100)),
                ("expiry_date", models.DateField()),
                ("manufacture_date", models.DateField()),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pharmacist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="main.pharmacist",
                    ),
                ),
            ],
        ),
    ]
