# Generated by Django 6.0.1 on 2026-01-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_order_orderitem_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
