# Generated by Django 6.0.1 on 2026-01-20 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_medicine_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="medicine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_items",
                to="main.medicine",
            ),
        ),
    ]
