# Generated by Django 6.0.1 on 2026-01-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_orderitem_medicine"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gst_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
