# Generated by Django 6.0.1 on 2026-01-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_order_gst_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="course_duration",
            field=models.CharField(
                blank=True,
                help_text="Expected duration of medicine course",
                max_length=50,
                null=True,
            ),
        ),
    ]
