# Generated by Django 6.0.1 on 2026-01-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_orderitem_course_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("successful", "Successful"),
                    ("failed", "Failed"),
                    ("delayed", "Delayed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
