# Generated by Django 6.0.1 on 2026-01-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="consulting_time_from",
            field=models.TimeField(
                blank=True, help_text="Consulting hours start time", null=True
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="consulting_time_to",
            field=models.TimeField(
                blank=True, help_text="Consulting hours end time", null=True
            ),
        ),
    ]
