# Generated by Django 6.0.1 on 2026-01-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_doctor_consulting_time_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Doctor's clinic location",
                max_length=200,
                null=True,
            ),
        ),
    ]
