# Generated by Django 6.0.1 on 2026-01-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("confirmed", "Confirmed"),
                    ("rescheduled", "Rescheduled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
