# Generated by Django 6.0.1 on 2026-01-24 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drug_name_generic",
                    models.CharField(
                        help_text="Generic name (mandatory)", max_length=200
                    ),
                ),
                (
                    "drug_name_brand",
                    models.CharField(
                        blank=True,
                        help_text="Brand name (optional)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        help_text="Strength/Potency (e.g., 500mg, 10ml)", max_length=50
                    ),
                ),
                (
                    "dosage_frequency",
                    models.CharField(
                        help_text="Dosage & Frequency (e.g., 1 tablet twice a day)",
                        max_length=100,
                    ),
                ),
                (
                    "route_administration",
                    models.CharField(
                        help_text="Route of Administration (e.g., Oral, Topical, IV)",
                        max_length=50,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text='Instructions (The "Sig") Relation to food and specific timing'
                    ),
                ),
                (
                    "total_quantity",
                    models.CharField(
                        help_text="Total number of pills or bottles to be dispensed",
                        max_length=50,
                    ),
                ),
                (
                    "duration_course",
                    models.CharField(
                        help_text='Duration of Course (e.g., "Take for 90 days")',
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="main.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.patient"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
