# Generated by Django 6.0.1 on 2026-01-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_prescription_delete_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="course_duration",
            field=models.CharField(
                blank=True,
                help_text="Expected duration of medicine course",
                max_length=50,
                null=True,
            ),
        ),
    ]
