# Generated by Django 6.0.1 on 2026-01-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_cart_course_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when refill reminder was sent",
                null=True,
            ),
        ),
    ]
