# Generated by Django 6.0.1 on 2026-01-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when notification was read", null=True
            ),
        ),
    ]
