# Generated by Django 6.0.1 on 2026-01-25 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="main.order",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="review_type",
            field=models.CharField(
                choices=[("doctor", "Doctor"), ("order", "Order")],
                default="doctor",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="main.doctor",
            ),
        ),
    ]
