# Generated by Django 6.0.1 on 2026-01-27 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_review_order_review_review_type_alter_review_doctor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="dosage_frequency",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="drug_name_brand",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="drug_name_generic",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="duration_course",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="instructions",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="route_administration",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="strength",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="total_quantity",
        ),
        migrations.CreateModel(
            name="PrescriptionMedicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drug_name_generic",
                    models.CharField(
                        help_text="Generic name (mandatory)", max_length=200
                    ),
                ),
                (
                    "drug_name_brand",
                    models.CharField(
                        blank=True,
                        help_text="Brand name (optional)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        help_text="Strength/Potency (e.g., 500mg, 10ml)", max_length=50
                    ),
                ),
                (
                    "dosage_frequency",
                    models.CharField(
                        help_text="Dosage & Frequency (e.g., 1 tablet twice a day)",
                        max_length=100,
                    ),
                ),
                (
                    "route_administration",
                    models.CharField(
                        help_text="Route of Administration (e.g., Oral, Topical, IV)",
                        max_length=50,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text='Instructions (The "Sig") Relation to food and specific timing'
                    ),
                ),
                (
                    "total_quantity",
                    models.CharField(
                        help_text="Total number of pills or bottles to be dispensed",
                        max_length=50,
                    ),
                ),
                (
                    "duration_course",
                    models.CharField(
                        help_text='Duration of Course (e.g., "Take for 90 days")',
                        max_length=100,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="main.prescription",
                    ),
                ),
            ],
        ),
    ]
