# Generated by Django 6.0.1 on 2026-01-27 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_remove_prescription_dosage_frequency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prescription_image",
                    models.ImageField(
                        help_text="Uploaded prescription image",
                        upload_to="prescription_uploads/",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Patient notes about the prescription",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("processed", "Processed"),
                            ("partially_available", "Partially Available"),
                            ("not_available", "Not Available"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_prescriptions",
                        to="main.patient",
                    ),
                ),
                (
                    "pharmacist",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pharmacy where prescription was uploaded. Null for common uploads.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_prescriptions",
                        to="main.pharmacist",
                    ),
                ),
            ],
        ),
    ]
