# Generated by Django 6.0.1 on 2026-01-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_prescriptionupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionupload",
            name="extracted_medicines",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of medicines extracted from prescription",
            ),
        ),
    ]
