# Generated by Django 6.0.1 on 2026-01-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_prescriptionupload_extracted_medicines"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionupload",
            name="available_medicines",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of available medicines with pharmacy info",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionupload",
            name="unavailable_medicines",
            field=models.JSONField(
                blank=True, default=list, help_text="List of unavailable medicines"
            ),
        ),
    ]
