# Generated by Django 6.0.1 on 2026-01-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_prescriptionupload_available_medicines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="medicine_type",
            field=models.CharField(
                choices=[("OTC", "Over-the-Counter"), ("Rx", "Prescription Required")],
                default="OTC",
                max_length=3,
            ),
        ),
    ]
