# Generated by Django 6.0.1 on 2026-01-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_medicine_medicine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="requires_prescription",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this medicine requires a prescription",
            ),
        ),
    ]
