# Generated by Django 6.0.1 on 2026-01-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_cart_requires_prescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="added_from_prescription",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this medicine was added to cart from a prescription",
            ),
        ),
    ]
