# Generated by Django 6.0.1 on 2026-02-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_cart_added_from_prescription"),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='next_appointment_date',
            field=models.DateField(null=True, blank=True, help_text="Date for the next appointment"),
        ),
    ]