# Generated by Django 6.0.1 on 2026-02-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_auto_20260201_1917"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("leave", "Leave"),
                ],
                default="inactive",
                help_text="Doctor's current availability status",
                max_length=10,
            ),
        ),
    ]
