# Generated by Django 6.0.1 on 2026-02-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_doctor_availability_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_from", models.DateField(help_text="Start date of leave")),
                (
                    "leave_to",
                    models.DateField(
                        help_text="End date of leave (same as start date for single day leave)"
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("personal", "Personal Leave"),
                            ("emergency", "Emergency Leave"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for leave")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="main.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Leave",
                "verbose_name_plural": "Doctor Leaves",
                "ordering": ["-leave_from"],
            },
        ),
    ]
