# Generated by Django 6.0.1 on 2026-02-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_leave"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                    ("pharmacist", "Pharmacist"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("prescription_created", "Prescription Created"),
                            ("prescription_edited", "Prescription Edited"),
                            ("prescription_deleted", "Prescription Deleted"),
                            ("appointment_created", "Appointment Created"),
                            ("appointment_updated", "Appointment Updated"),
                            ("appointment_deleted", "Appointment Deleted"),
                            ("medicine_added", "Medicine Added"),
                            ("medicine_updated", "Medicine Updated"),
                            ("medicine_deleted", "Medicine Deleted"),
                            ("order_created", "Order Created"),
                            ("order_updated", "Order Updated"),
                            ("order_deleted", "Order Deleted"),
                            ("profile_updated", "Profile Updated"),
                            ("leave_set", "Leave Set"),
                            ("availability_updated", "Availability Status Updated"),
                            ("other", "Other Action"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the action",
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of related object (e.g., prescription ID)",
                        null=True,
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of related object (e.g., Prescription, Appointment)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="main.users",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="main_auditl_user_id_5c7864_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="main_auditl_action_17a227_idx",
                    ),
                ],
            },
        ),
    ]
