# Generated by Django 6.0.1 on 2026-02-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_users_last_login_alter_users_role_auditlog"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="CustomUser",
        ),
    ]
