# Generated by Django 6.0.1 on 2026-02-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_rename_users_customuser"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomUser",
            new_name="Users",
        ),
    ]
