# Generated by Django 6.0 on 2026-02-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_rename_customuser_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="card_cvv",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="card_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="card_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
