# Generated by Django 6.0 on 2026-02-04 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0041_transaction_card_cvv_transaction_card_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_name",
                    models.CharField(help_text="Name of the lab test", max_length=200),
                ),
                (
                    "test_category",
                    models.CharField(
                        choices=[
                            ("blood", "Blood Test"),
                            ("urine", "Urine Test"),
                            ("imaging", "Imaging/Radiology"),
                            ("pathology", "Pathology"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "test_description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the test",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("routine", "Routine"), ("urgent", "Urgent")],
                        default="routine",
                        max_length=10,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Special instructions for the patient",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_tests",
                        to="main.prescription",
                    ),
                ),
            ],
        ),
    ]
