# Generated by Django 6.0.1 on 2026-02-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_orderitem_reminder_sent_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="course_duration",
        ),
    ]