# Generated by Django 6.0 on 2026-02-04 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0042_labtest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="main.appointment",
            ),
        ),
    ]
