# Generated by Django 6.0 on 2026-02-06 15:07

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_prescription_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Lab report image file', upload_to=main.models.lab_report_image_path)),
                ('report_name', models.CharField(help_text='Name/description of the lab report', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the lab report', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_report_images', to='main.patient')),
            ],
        ),
    ]
