# Generated by Django 6.0.1 on 2026-02-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0043_remove_cart_course_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="course_duration",
        ),
    ]