# Generated by Django 6.0 on 2026-02-14 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0044_labreportimage"),
        ("main", "0044_remove_orderitem_course_duration"),
    ]

    operations = []
