# Generated by Django 6.0 on 2026-02-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0045_merge_20260214_1105"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="course_duration",
            field=models.CharField(
                blank=True,
                help_text="Expected duration of medicine course",
                max_length=50,
                null=True,
            ),
        ),
    ]
