# Generated by Django 6.0 on 2026-02-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_orderitem_course_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="course_duration",
        ),
    ]
