# Generated by Django 6.0 on 2026-02-16 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0049_remove_orderitem_course_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_name",
                    models.CharField(
                        help_text="Name of the medical condition", max_length=200
                    ),
                ),
                (
                    "diagnosis_date",
                    models.DateField(help_text="Date when the condition was diagnosed"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the condition",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("chronic", "Chronic"),
                            ("remission", "In Remission"),
                        ],
                        default="active",
                        help_text="Current status of the condition",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the condition",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_conditions",
                        to="main.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PastOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_name",
                    models.CharField(
                        help_text="Name of the surgical operation/procedure",
                        max_length=200,
                    ),
                ),
                (
                    "operation_date",
                    models.DateField(help_text="Date when the operation was performed"),
                ),
                (
                    "surgeon",
                    models.CharField(
                        blank=True,
                        help_text="Name of the surgeon who performed the operation",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "hospital_clinic",
                    models.CharField(
                        blank=True,
                        help_text="Name of the hospital or clinic where operation was performed",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the operation",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the operation",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="past_operations",
                        to="main.patient",
                    ),
                ),
            ],
        ),
    ]
