# Generated by Django 6.0 on 2026-02-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0050_medicalcondition_pastoperation"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_mode",
            field=models.CharField(
                choices=[
                    ("home_delivery", "Home Delivery"),
                    ("in_store_pickup", "In-Store Pickup"),
                ],
                default="home_delivery",
                max_length=20,
            ),
        ),
    ]
