# Generated by Django 6.0 on 2026-02-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0051_order_delivery_address_order_delivery_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("preparing", "Preparing"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("delayed", "Delayed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
