# Generated by Django 6.0 on 2026-02-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0052_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="scheduled_delivery_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Scheduled delivery date set by pharmacist",
                null=True,
            ),
        ),
    ]
