# Generated by Django 6.0.1 on 2026-03-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_notification_pharmacist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='duration_course',
        ),
        migrations.DeleteModel(
            name='PrescriptionUpload',
        ),
    ]
