# Generated by Django 6.0.1 on 2026-03-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_remove_prescriptionmedicine_duration_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text="Doctor's registration approval status", max_length=10),
        ),
    ]
