# Generated by Django 6.0.1 on 2026-03-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_doctor_registration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='route_administration',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='total_quantity',
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='strength',
            field=models.CharField(blank=True, help_text='Strength/Potency (e.g., 500mg, 10ml)', max_length=50, null=True),
        ),
    ]
