# Generated by Django 6.0.1 on 2026-03-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_remove_prescriptionmedicine_route_administration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text='Duration of medicine course in days', null=True),
        ),
    ]
