# Generated by Django 6.0.1 on 2026-03-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_prescriptionmedicine_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('out_for_delivery', 'Out for Delivery'), ('ready_for_pickup', 'Ready for Pickup'), ('completed', 'Completed'), ('failed', 'Failed'), ('delayed', 'Delayed')], default='pending', max_length=20),
        ),
    ]
